P2P peer broadcast and discovery
mitre/sandcat pull request #337
Opened 2020-11-30 18:43 UTC by mrengstrom

adding mDNS broadcaster to the http proxy extension

2020-12-03 23:06 UTC, unkempthenry requested changes
What are your thoughts on adding?: 

- a variation(s) to the sandcat deploy ability that has the headers and options to get this running
- supporting something like a `-server null` argument to force the agent to use p2p

2020-12-03 23:06 UTC, unkempthenry commented on gocat-extensions/proxy/proxy_receiver_http.go
> +//     info = h.urlList
extraneous comment?

2020-12-04 15:10 UTC, mrengstrom commented on gocat-extensions/proxy/proxy_receiver_http.go
> +//     info = h.urlList
yup, looks like I missed that.  Will remove.

2020-12-15 21:47 UTC, unkempthenry approved these changes

2020-12-15 21:47 UTC, unkempthenry commented
depends on https://github.com/mitre/gocat/pull/33

2021-01-07 15:06 UTC, merged