Initial framework for dns tunneling
mitre/sandcat pull request #351
Opened 2021-02-18 21:23 UTC by uruwhy

## Description
Initial framework for DNS tunneling contact as gocat extension. Does not yet support file uploads.

## Type of change
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?
Ran operations with agents on windows, linux, and Mac. tested abilities that downloaded payloads and submitted results back to the C2.

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2021-03-08 14:16 UTC, mrengstrom commented on gocat-extensions/contact/dns_tunneling.go
> +	//return fmt.Sprintf("%s.%s.%d.%d.%s.%s", messageID, messageType, chunkIndex, numChunks, dataHex, BASE_DOMAIN), nil
is the comment needed?  Seems like it can be dropped.

2021-03-08 14:49 UTC, uruwhy commented on gocat-extensions/contact/dns_tunneling.go
> +	//return fmt.Sprintf("%s.%s.%d.%d.%s.%s", messageID, messageType, chunkIndex, numChunks, dataHex, BASE_DOMAIN), nil
good eye, can't remember why I left that in there. I'll clean up some other vestigial comments that are hanging around as well

2021-03-08 14:50 UTC, uruwhy commented on gocat-extensions/contact/dns_tunneling.go
> +	//return fmt.Sprintf("%s.%s.%d.%d.%s.%s", messageID, messageType, chunkIndex, numChunks, dataHex, BASE_DOMAIN), nil
Ah, I think the DNS library I used for golang required qnames to end with a ".", hence line 267. Regardless, I'll remove the old comment

2021-03-08 19:11 UTC, wbooth requested changes
.

2021-03-09 12:17 UTC, uruwhy commented on gocat-extensions/contact/dns_tunneling.go
> +	//return fmt.Sprintf("%s.%s.%d.%d.%s.%s", messageID, messageType, chunkIndex, numChunks, dataHex, BASE_DOMAIN), nil
fixed

2021-03-09 14:33 UTC, mrengstrom approved these changes

2021-03-09 19:01 UTC, merged