VIRTS-1709: Adding python executor to sandcat
mitre/sandcat pull request #357
Opened 2021-03-12 01:48 UTC by blackwidow0616

## Description

Adding python executors for sandcat and checks the version of python on the system and returns the appropriate executor name (supports python3 and python2).

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

This works on Windows (10) and *nix (ubuntu 18 & macos) with python3 (executed via python[.exe] or python3[.exe]) and python2. If a system has both versions, two python executors are made. 

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

2021-03-12 14:38 UTC, protoli commented on gocat-extensions/execute/shells/python.go
> +	setExecutor("python")
next step would be to have this attempt to create executors based on a number of different potential python versions that are commonly seen (i.e. 2, 2.7, etc) as right now it only covers the python3 and python cases

2021-03-12 14:41 UTC, protoli commented on gocat-extensions/execute/shells/python.go
> +	str_ver = string(version)
TrimSpace should remove all whitespace with a single line

2021-03-12 14:42 UTC, protoli commented on gocat-extensions/execute/shells/python.go
> +	str_ver = strings.TrimSuffix(str_ver, "\n")
TrimSpace should remove all whitespace with a single line

2021-03-12 16:31 UTC, garunagiri commented on gocat-extensions/execute/shells/python.go
> +	setExecutor("python")
A possible way to deal with this is to check for python on Windows using `py` rather than the full `python`.
https://timothybramlett.com/To-run-Python-2-and-3-side-by-side-on-Windows.html

2021-03-12 19:52 UTC, uruwhy requested changes

2021-03-12 19:54 UTC, blackwidow0616 commented on gocat-extensions/execute/shells/python.go
> +	version, err := exec.Command("python", "-c", "import platform; print(platform.python_version().split('.')[0])").CombinedOutput()
How it's currently implemented it only comes to this function if it's executed via "python" - if it executes via "python3" it currently assumes that it's version 3

2021-03-15 16:48 UTC, protoli approved these changes

2021-03-15 17:48 UTC, uruwhy requested changes
once that comment is removed, we'll be good to go

2021-03-15 17:48 UTC, uruwhy commented on gocat-extensions/execute/shells/python.go
> +//	"github.com/mitre/gocat/output"
we'll just delete this

2021-03-15 18:32 UTC, protoli approved these changes

2021-03-16 14:53 UTC, merged