Ftp
mitre/sandcat pull request #373
Opened 2021-08-11 20:38 UTC by Sloane4

## Description

Files to control agent communication with ftp server to conduct Beaconing, Payload Requests, File Upload, and Send Execution Results. 

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Manually, deployment of agent on Linux and Windows OS & all operations ran with multiple agents running.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2021-08-12 13:34 UTC, uruwhy requested changes
Looking really good! Just a few more things here and there - it also looks like there are still some indentation issues in ftp.go.

2021-08-12 13:34 UTC, uruwhy commented on gocat-extensions/contact/ftp.go
> +    connect := f.UploadFile("Payload.txt", payloadReq)
Also, it might be easier to just call UploadFileBytes and avoid having to call ServerSetDir and UploadFile repeatedly

2021-08-12 13:34 UTC, uruwhy commented on gocat-extensions/contact/ftp.go
> +    //newData := bytes.NewBufferString(data)
remove unnecesary comments

2021-08-12 13:34 UTC, uruwhy commented on gocat-extensions/contact/ftp.go
> +	if uploadName != "Alive.txt"{
If you're going to call `UploadFileBytes` from `DownloadPayload`, make sure to add `Payload.txt` to this condition

2021-08-16 13:23 UTC, uruwhy requested changes
Few more changes to request, including a few remaining indentation issues

2021-08-16 13:23 UTC, uruwhy commented on app/extensions/contact/ftp.py
> +                raise Exception('No variable specified in C2 configuration file under '+var)
spaces between `+` operator

2021-08-16 13:23 UTC, uruwhy commented on gocat-extensions/contact/ftp.go
> +	}
There's still a few indentation issues

2021-08-16 13:23 UTC, uruwhy commented on gocat-extensions/contact/ftp.go
> +    rand.Seed(time.Now().UnixNano())
This function and `getNewUploadId` do the exact same thing - maybe you can just have one function called `getRandomId`?

2021-08-16 13:23 UTC, uruwhy commented on gocat-extensions/contact/ftp.go
> +    connect := f.UploadFileBytes(profile, "Alive.txt", data)
rename variable as "err" or something like that

2021-08-18 13:42 UTC, uruwhy commented on app/extensions/contact/ftp.py
> +                print('No variable specified in C2 configuration file under ' + var)
Rename `ConfigFileError` to `ConfigFileException` and then instead of `print`, just call `raise ConfigFileException(blah blah blah)` so you can set the exception message

2021-08-18 13:44 UTC, uruwhy commented on app/extensions/contact/ftp.py
> +class ConfigFileError(Exception):
can you move this class to `sandcat/app/utility/base_extension.py` ?

2021-08-18 13:45 UTC, uruwhy commented on app/extensions/contact/ftp.py
> +    """Raised when no variable specified in C2 configuration file under"""
"Raise this exception when a required variable or setting for the extension is not specified in the C2 configuration file"

2021-08-18 13:49 UTC, uruwhy commented on gocat-extensions/contact/ftp.go
> +    //newData := bytes.NewBufferString(data)
don't forget to clear out old/unnecessary comments

2021-08-18 13:49 UTC, uruwhy commented on gocat-extensions/contact/ftp.go
> +    connect := f.UploadFile(uniqueFileName, data)
change to `connectErr` or reuse `errConn`

2021-08-18 19:11 UTC, uruwhy commented on app/extensions/contact/ftp.py
> +DOMAIN_CONFIG = ['app.contact.ftp.user', 'app.contact.ftp.pword', 'app.contact.ftp.server.dir']
This name will need to be refactored, since it's only relevant for DNS tunneling. We can call it something like `FTP_CONFIG_VARIABLES`

2021-08-18 19:15 UTC, uruwhy commented on gocat-extensions/contact/ftp.go
> +//Return upstreamDestAddr
This function sets upstreamDestAddr rather than returning anything

2021-08-18 19:15 UTC, uruwhy commented on gocat-extensions/contact/ftp.go
> +//If no paw, create one
This comment is no longer relevant - you can remove it

2021-08-18 20:31 UTC, uruwhy commented on gocat-extensions/contact/ftp.go
> +    f.beacon = BEACON
if you don't plan on changing the BEACON, PAYLOAD, and RESPONSE constants, you don't have to assign them to `f`. Instead, just refer to the constants throughout `ftp.go`. Though maybe you can rename then to `BEACON_FILENAME`, `PAYLOAD_FILENAME`, etc

2021-08-18 20:34 UTC, uruwhy commented on gocat-extensions/contact/ftp.go
> +    }
don't forget to handle the outer `err` if it isn't nil. Something like `output.VerbosePrint(fmt.Sprintf("[!] Error marshaling profile copy: %s", err.Error()))`

2021-08-18 20:36 UTC, uruwhy commented on gocat-extensions/contact/ftp.go
> +    if errUpload != nil {
optional: if you want to shorten this, you can simply say `return f.UploadFile(uniqueFileName, data)`, since either way it'll be nil or you're returning that exact error

2021-08-18 20:38 UTC, uruwhy commented on gocat-extensions/contact/ftp.go
> +        f.client.ChangeDir(f.directory + "/" + paw)
make this a return, so we also catch the edge case where this causes an error for some reason

`return f.client.ChangeDir(f.directory + "/" + paw)`

2021-08-18 20:41 UTC, uruwhy commented on gocat-extensions/contact/ftp.go
> +        output.VerbosePrint(fmt.Sprintf("[-] Failed to download file from FTP Server: %s", err.Error()))
Question - do we want to add retries in case there's some lag in between the server processing the Beacon.txt upload and actually writing the response file?

2021-08-18 20:44 UTC, uruwhy commented on gocat-extensions/contact/ftp.go
> +    data, err := f.DownloadFile(payloadName)
question - do we want to add retries in case of lag / delays from the server? Or is that already built into the FTP framework?

2021-08-18 20:51 UTC, uruwhy commented on gocat-extensions/contact/ftp.go
> +        f.client.Delete(f.beacon)
shouldn't this only occur in `FtpBeacon`? We don't want to attempt to delete the beacon file every time we download some file, since not all file downloads will be for beacon responses

2021-08-18 20:51 UTC, uruwhy commented on gocat-extensions/contact/ftp.go
> +        f.client.Delete(f.beacon)
Never mind, I didn't catch the above if-statement. Disregard!

2021-08-19 14:45 UTC, Sloane4 commented on gocat-extensions/contact/ftp.go
> +        output.VerbosePrint(fmt.Sprintf("[-] Failed to download file from FTP Server: %s", err.Error()))
I don't think that is necessary because the ftp server does not send a upload file finished until the response.txt file is written. If I am understanding golang correctly, it wont try to download the file until the upload is finished.

2021-08-19 15:08 UTC, uruwhy commented on gocat-extensions/contact/ftp.go
> +        output.VerbosePrint(fmt.Sprintf("[-] Failed to download file from FTP Server: %s", err.Error()))
Gotcha - and that's because the server writes the response file before sending `'226', 'data transfer done'`

2021-08-19 15:09 UTC, uruwhy commented on gocat-extensions/contact/ftp.go
> +    data, err := f.DownloadFile(payloadName)
resolving for same reason as above

2021-08-19 20:11 UTC, uruwhy commented on gocat-extensions/contact/ftp.go
> +    RESULT_FILENAME = "Alive.txt" //"Results.txt"
remove comment if you're not going to change the filename now

2021-08-19 20:14 UTC, uruwhy commented on gocat-extensions/contact/ftp.go
> +        output.VerbosePrint("[!] Error converting profile map to String - cannot send BEACON_FILENAME")
if you meant to actually print the beacon filename, use `fmt.Sprintf`

2021-08-19 20:33 UTC, uruwhy approved these changes
Great job!

2021-08-20 13:05 UTC, merged