Check option before removing payloads
mitre/sandcat pull request #404
Opened 2022-02-11 20:57 UTC by clenk

## Description

Makes payload auto-removal optional.

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Tested with core PR: https://github.com/mitre/caldera/pull/2482.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code

2022-02-12 00:05 UTC, cyber-arsenull requested changes

2022-02-14 21:46 UTC, clenk commented on gocat/agent/agent.go
> +	    a.removePayloadsOnDisk(onDiskPayloads)
`onDiskPayloads` only holds the payloads for this 1 specific instruction. So in the example scenario, Ability 2 will remove its payload but not the payload from Ability 1. Then Ability 3 will result in the agent downloading the payload bytes but it won't write it to a file because `[*] File %s already exists`. Ability 3 will run fine though.

One improvement could be to check if the file exists before downloading the bytes at all, to reduce network traffic.

2022-02-23 16:21 UTC, uruwhy approved these changes

2022-04-05 17:43 UTC, cyber-arsenull approved these changes

2022-04-05 19:46 UTC, merged