[VIRTS-4690] Add Architecture Header to Sandcat
mitre/sandcat pull request #435
Opened 2023-09-11 14:16 UTC by bleepbop

## Description
Allows users to supply an architecture header to sandcat. This will allow Darwin ARM64 users to successfully compile sandcat without emulation.

## Type of change
- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

## How Has This Been Tested?
Ran all of new agent commands for ARM64, and ran a few abilities with each. Agents compiled successfully and were able to transmit data successfully as well. When running `file splunkd`, the output verified that the agent was compiled for ARM64.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2023-09-26 23:04 UTC, elegantmoose approved these changes

2023-09-26 23:05 UTC, elegantmoose commented
Code looked good but I could not test out ARM on my Mac.

2023-10-02 21:28 UTC, clenk requested changes
The original PR also updated `update-agents.sh`  and the list of precompiled binaries on the docs page - can you update those as well?

For the docs page, I would prefer adding `architecture` to the list of parameters and explaining it there instead of at the top of the `Options` section.

2023-10-16 16:57 UTC, clenk approved these changes
LGTM!

2023-10-16 16:58 UTC, merged